"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more 
letter at a random position.

Return the letter that was added to t:
>>> find_difference("abcd", "abcde")
'e'
>>> find_difference("", "y")
'y'
>>> find_difference("a", "aa")
'a'
>>> find_difference("ae", "aea")
'a'
"""

def find_difference(s, t):
    """Return difference between two strings"""
    pass




if __name__ == '__main__':
    import doctest
    if doctest.testmod().failed == 0:
        print('\n ✨ALL TESTS PASS! Drink coffee and come back to work! ✨')