"""You are given two strings s and t.

String t is generated by random shuffling string s and then add one more 
letter at a random position.

Return the letter that was added to t:
>>> find_difference("abcd", "abcde")
'e'
>>> find_difference("", "y")
'y'
>>> find_difference("a", "aa")
'a'
>>> find_difference("ae", "aea")
'a'
"""

def find_difference(s, t):
    """Return difference between two strings"""
    hash_map = {}
        
    for char in t:
        if char not in hash_map:
            hash_map[char] = 1
        else:
            hash_map[char]+= 1
            
    for char in s:
        if char in hash_map:
            hash_map[char]-= 1
            
    
    for key in hash_map:
        if hash_map[key] == 1:
            return key




if __name__ == '__main__':
    import doctest
    if doctest.testmod().failed == 0:
        print('\n ✨ALL TESTS PASS! Drink coffee and come back to work! ✨')